### ISSUE TITLE
"Ye Own Booty" tab scrolls entire screen, instead of just RecyclerView

### ISSUE THREAD

**Issue by jhernandez5922** [adamhabib25/MessageInABottle#5]
Should be an easy fix. Leaving here because it's small enough bug to forget about

**Comment by BrennenFagan** [comment]
I was under the impression that this was a feature, rather than a bug, but
I'm fine either way.

-Brennen Fagan

**Comment by jhernandez5922** [comment]
Only issue is that when you scroll down then swipe to the next tab, it doesn't auto scroll up. You can't see to the ActionBar or the Tabs if that happens.

**Comment by BrennenFagan** [comment]
That, on the other hand is an actual issue. Would it be easier to shift the
layout so that it does just scroll the RecyclerView or would it be easier
to just tell it to switch to the top when it swipes to the next tab?

Brennen Fagan

Math Department - Instructional Student Assistant for Math 6

Chemistry Club - Treasurer for the 2015-2016 year

rydrion@mail.fresnostate.edu

brennenfagan@gmail.com

**Comment by jhernandez5922** [comment]
I think it becomes an aesthetic issue at that point, so I am in favor of keeping the ActionBar and TabBar static at the top, but the auto scrolling to the top is another option.

**Comment by BrennenFagan** [comment]
I believe that our UI changes have addressed this issue as of now.
